# 🔹 1. What is Pandas?

Pandas (Python library) is a powerful Python library used for:

Data cleaning
Data manipulation
Data analysis

like we learned in 2d numpy array pandas work on dataframes , pandas built on top of numpy 
dataframe is combination of rows and columns 
we can create our own dataframe as well as we can import file like csv excel json etc

In [2]:
#here we are creating our own dataframe 

import pandas as pd

data = {
  
    "title": [
        "Inception", "Titanic", "Avengers: Endgame", "The Dark Knight",
        "Interstellar", "Joker", "3 Idiots", "Dangal"
    ],
    "genre": [
        "Sci-Fi", "Romance", "Action", "Action",
        "Sci-Fi", "Drama", "Comedy", "Sports"
    ],
    "director": [
        "Christopher Nolan", "James Cameron", "Anthony Russo",
        "Christopher Nolan", "Christopher Nolan",
        "Todd Phillips", "Rajkumar Hirani", "Nitesh Tiwari"
    ],
    "year": [2010, 1997, 2019, 2008, 2014, 2019, 2009, 2016],
    "rating": [8.8, 7.8, 8.4, 9.0, 8.6, 8.5, 8.4, 8.3],
    "revenue_million": [829, 2200, 2797, 1005, 677, 1074, 392, 340]
}

df = pd.DataFrame(data)

print(df)

               title    genre           director  year  rating  \
0          Inception   Sci-Fi  Christopher Nolan  2010     8.8
1            Titanic  Romance      James Cameron  1997     7.8
2  Avengers: Endgame   Action      Anthony Russo  2019     8.4
3    The Dark Knight   Action  Christopher Nolan  2008     9.0
4       Interstellar   Sci-Fi  Christopher Nolan  2014     8.6
5              Joker    Drama      Todd Phillips  2019     8.5
6           3 Idiots   Comedy    Rajkumar Hirani  2009     8.4
7             Dangal   Sports      Nitesh Tiwari  2016     8.3

   revenue_million
0              829
1             2200
2             2797
3             1005
4              677
5             1074
6              392
7              340

In [3]:
df.head() #df head() will give you top 5 rows from dataset to have a view of data

,title,genre,director,year,rating,revenue_million
0,Inception,Sci-Fi,Christopher Nolan,2010,8.8,829
1,Titanic,Romance,James Cameron,1997,7.8,2200
2,Avengers: Endgame,Action,Anthony Russo,2019,8.4,2797
3,The Dark Knight,Action,Christopher Nolan,2008,9.0,1005
4,Interstellar,Sci-Fi,Christopher Nolan,2014,8.6,677

In [4]:
df.tail() #similarly tail() will give you last 5 rows

             title   genre           director  year  rating  revenue_million
3  The Dark Knight  Action  Christopher Nolan  2008     9.0             1005
4     Interstellar  Sci-Fi  Christopher Nolan  2014     8.6              677
5            Joker   Drama      Todd Phillips  2019     8.5             1074
6         3 Idiots  Comedy    Rajkumar Hirani  2009     8.4              392
7           Dangal  Sports      Nitesh Tiwari  2016     8.3              340

In [5]:
df.info() #info() will give you information about dataset from here we can see if any col has null values of not

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 6 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   title            8 non-null      object
 1   genre            8 non-null      object
 2   director         8 non-null      object
 3   year             8 non-null      int64
 4   rating           8 non-null      float64
 5   revenue_million  8 non-null      int64
dtypes: float64(1), int64(2), object(3)
memory usage: 512.0+ bytes

In [6]:
df.isnull() #similarly isnull() will check if any value is null or not

   title  genre  director   year  rating  revenue_million
0  False  False     False  False   False            False
1  False  False     False  False   False            False
2  False  False     False  False   False            False
3  False  False     False  False   False            False
4  False  False     False  False   False            False
5  False  False     False  False   False            False
6  False  False     False  False   False            False
7  False  False     False  False   False            False

In [7]:
df.describe() #describe will give you another level of mathematical information min max std dv count of rows etc

              year    rating  revenue_million
count     8.000000  8.000000         8.000000
mean   2011.500000  8.475000      1164.250000
std       7.270292  0.357571       878.124584
min    1997.000000  7.800000       340.000000
25%    2008.750000  8.375000       605.750000
50%    2012.000000  8.450000       917.000000
75%    2016.750000  8.650000      1355.500000
max    2019.000000  9.000000      2797.000000

## Reading data using pandas 
1) Reading data using csv (comma seperated values) df = pd.read_csv("path.csv") csv doesnt have multiple sheets
2) Reading data using excel df = pd.read_excel(path.xlsx) - when we have multiple sheets in excel
3) Reading data using json df = pd.read_json(path.json) or we can pass json url

In [8]:
# Okay lets read some excel file random 
import pandas as pd
df = pd.read_excel(r"C:\Users\namitjai\Desktop\learning\data.xlsx")

In [9]:
df

   area manager   area  sales
0         rahul  north   2500
1         kamal  south   3000
2         sunil   east   4555
3         deepu   west    564
4        anurag   west   5644
5       durgesh   west   5646
6         sahil  south   3623
7        preeti  south   6549
8         nisha   east   3123
9         rohan   east     33
10        kadar  north    333
11       rakesh  north   8757

## Selecting some column like we do in sql
1) column based -->>
select col1, col2 from table 

df = df['col1'] - > this is when we need to select only 1 column but this gives series not dataframe
df = df[['col1','col2','col3']] -->> this is when we need to select two or more columns this will give you a dataframe explained below

2) row based --->>

df.iloc[0]          # first row (index-based)
df.loc[0]           # first row (label-based)

Two Ways Pandas Accesses Data
1. 🔢 iloc → Index-based (position-based)
df.iloc[0]

👉 Means:
“Give me the row at position 0 (first row), no matter what the label is.”

Works like Python lists
Always uses integer positions: 0, 1, 2, 3...
2. 🏷️ loc → Label-based
df.loc[0]

👉 Means:
“Give me the row whose index label is 0”

Uses index names/labels, not position
Labels can be anything: numbers, strings, dates

In [10]:
df_one_col = df['area manager']

In [11]:
df_one_col # it gave all the rows inside col area manager with index but i cant see col header as its a series

0       rahul
1       kamal
2       sunil
3       deepu
4      anurag
5     durgesh
6       sahil
7      preeti
8       nisha
9       rohan
10      kadar
11     rakesh
Name: area manager, dtype: object

📌 Why does it look like it has “no header”?

A Series actually does have a header, but it’s stored differently

🔍 Explanation:
0, 1, 2 → index
John, Alice, Bob → values
Name: area manager → ✅ this is the column header

👉 So the header is there — just shown at the bottom, not on top like in a DataFrame.

In [12]:
print(type(df_one_col))

<class 'pandas.core.series.Series'>

In [13]:
#now if we do [[]] this is a dataframe
df_one_col = df[['area manager']]

In [14]:
df_one_col

   area manager
0         rahul
1         kamal
2         sunil
3         deepu
4        anurag
5       durgesh
6         sahil
7        preeti
8         nisha
9         rohan
10        kadar
11       rakesh

In [15]:
#now selecting muliple columns

df_multi = df[['area manager','area']]

In [16]:
df_multi

   area manager   area
0         rahul  north
1         kamal  south
2         sunil   east
3         deepu   west
4        anurag   west
5       durgesh   west
6         sahil  south
7        preeti  south
8         nisha   east
9         rohan   east
10        kadar  north
11       rakesh  north

In [17]:
#now if you see there is a index 0 to 11 follows every row its like a list 
#we can access rows using this index or using labels (if we creata area manager as index) lets play using iloc and loc

df.iloc[1] # we have given index here

area manager    kamal
area            south
sales            3000
Name: 1, dtype: object

In [18]:
df.loc[1] # we have given index here

area manager    kamal
area            south
sales            3000
Name: 1, dtype: object

In [19]:
df.loc[1:3] # we have done list slicing here

  area manager   area  sales
1        kamal  south   3000
2        sunil   east   4555
3        deepu   west    564

In [20]:
df.iloc[1:3] # we have done slicing here but you see 3 is not included

  area manager   area  sales
1        kamal  south   3000
2        sunil   east   4555

In [21]:
#now we are setting index as col 1 area manager

df_new = df.set_index('area manager')

In [22]:
df_new.loc['rahul'] #now we are using area manager name as index and searching using this

area     north
sales     2500
Name: rahul, dtype: object

In [23]:
df_new.iloc['rahul'] # but see iloc doesnt work here as its iloc - integer location

TypeError: Cannot index by location index with a non-integer key

In [ ]:
df_new.iloc[2]

 ## Filtering using pandas
 
 df[df["Age"] > 23]
 
 this is like where condition in sql 
 
 select all the rows where age is greater than 23
 
 SELECT * FROM df_new WHERE sales > 2000;
 
 we can also use df.query('condition')

In [29]:
df_new[df_new["sales"] > 2000]

               area  sales
area manager
rahul         north   2500
kamal         south   3000
sunil          east   4555
anurag         west   5644
durgesh        west   5646
sahil         south   3623
preeti        south   6549
nisha          east   3123
rakesh        north   8757

In [33]:
df_new.query('sales > 2000' and 'area == "north"')

               area  sales
area manager
rahul         north   2500
kadar         north    333
rakesh        north   8757

order by 

SELECT * FROM df_new ORDER BY sales DESC;

In [35]:
df_new.sort_values(by = 'sales',ascending=False)

               area  sales
area manager
rakesh        north   8757
preeti        south   6549
durgesh        west   5646
anurag         west   5644
sunil          east   4555
sahil         south   3623
nisha          east   3123
kamal         south   3000
rahul         north   2500
deepu          west    564
kadar         north    333
rohan          east     33

### Group By 
In pandas, groupby is most commonly used with aggregation, but it’s not limited to it.

Typical use:

df.groupby("dept")["salary"].mean()

This collapses rows → one result per group.

🔹 2. Can we do row-level (window-like) operations?

Yes—you can, but not with .agg().

For row-level results (like SQL window functions), you use:

✅ transform() (closest to window functions)
df["dept_avg_salary"] = df.groupby("dept")["salary"].transform("mean")
in sql :-  AVG(salary) OVER (PARTITION BY dept)

👉 This keeps the same number of rows as the original DataFrame
👉 Each row gets its group’s aggregate value

This is very similar to:

AVG(salary) OVER (PARTITION BY dept)




3. ROW_NUMBER() OVER (PARTITION BY dept ORDER BY salary)
SQL
ROW_NUMBER() OVER (PARTITION BY dept ORDER BY salary)

Pandas
df["row_number"] = df.sort_values(["dept", "salary"]) \
                     .groupby("dept") \
                     .cumcount() + 1

In [45]:
import pandas as pd

df = pd.DataFrame({
    "dept": ["A", "A", "A", "B", "B"],
    "emp":  ["e1","e2","e3","e4","e5"],
    "salary": [10, 20, 30, 40, 50]
})

In [37]:
df

  dept emp  salary
0    A  e1      10
1    A  e2      20
2    A  e3      30
3    B  e4      40
4    B  e5      50

In [ ]:
#average salary by department | SQL :- select emp , avg(salary) from df group by emp

In [38]:
df.groupby('dept').mean('salary')

      salary
dept
A       20.0
B       45.0

In [39]:
#row level aggragtion like row number we use tranform()

  dept emp  salary
0    A  e1      10
1    A  e2      20
2    A  e3      30
3    B  e4      40
4    B  e5      50

In [46]:
df['avg_salary_per_dept'] = df.groupby('dept').transform("mean")

C:\Users\namitjai\AppData\Local\Temp\ipykernel_24340\473999284.py:1: FutureWarning: The default value of numeric_only in DataFrameGroupBy.mean is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  df['avg_salary_per_dept'] = df.groupby('dept').transform("mean")

In [47]:
df

  dept emp  salary  avg_salary_per_dept
0    A  e1      10                 20.0
1    A  e2      20                 20.0
2    A  e3      30                 20.0
3    B  e4      40                 45.0
4    B  e5      50                 45.0

In [56]:
df['row_numberrr'] = df.sort_values('dept').groupby('dept').cumcount()

In [57]:
df #cumcount() +1 if row_number , cumcount()-1 in row_numberr and cumcount() is row_numberr so best is cumcount +1 just like sql

  dept emp  salary  avg_salary_per_dept  row_number  row_numberr  row_numberrr
0    A  e1      10                 20.0           1           -1             0
1    A  e2      20                 20.0           2            0             1
2    A  e3      30                 20.0           3            1             2
3    B  e4      40                 45.0           1           -1             0
4    B  e5      50                 45.0           2            0             1

In [59]:
df.query('row_number == 1')

  dept emp  salary  avg_salary_per_dept  row_number  row_numberr  row_numberrr
0    A  e1      10                 20.0           1           -1             0
3    B  e4      40                 45.0           1           -1             0

In [61]:
df[df["row_number"] == 1]

  dept emp  salary  avg_salary_per_dept  row_number  row_numberr  row_numberrr
0    A  e1      10                 20.0           1           -1             0
3    B  e4      40                 45.0           1           -1             0

## Handling Missing Data

In real datasets, you’ll constantly see missing values like:

NaN
None
empty cells

In [62]:
import pandas as pd

data = {
    "Name": ["Amit", "Riya", "Raj", None],
    "Age": [25, None, 30, 22],
    "City": ["Delhi", "Mumbai", None, "Jaipur"]
}

df = pd.DataFrame(data)
print(df)

   Name   Age    City
0  Amit  25.0   Delhi
1  Riya   NaN  Mumbai
2   Raj  30.0    None
3  None  22.0  Jaipur

In [ ]:
#we see None and NaN in thi dataset 
# 1) we will check if there are any null values or not

In [63]:
df.isna() #all true values are nulls

    Name    Age   City
0  False  False  False
1  False   True  False
2  False  False   True
3   True  False  False

In [64]:
df.isna().sum() #this is perfect to see how many null values per column we have this is perfect to check in large dataset

Name    1
Age     1
City    1
dtype: int64

#now we know we have null values and we counted also we have two options either we drop the rows or fill the null values
Drop Missing Data

Remove rows with missing values:

df.dropna()

Remove columns with missing values:

df.dropna(axis=1)

In [65]:
df.dropna() #it has dropped all the rows there it found any missing value

   Name   Age   City
0  Amit  25.0  Delhi

In [66]:
df

   Name   Age    City
0  Amit  25.0   Delhi
1  Riya   NaN  Mumbai
2   Raj  30.0    None
3  None  22.0  Jaipur

In [67]:
df.dropna(axis = 1) #it has dropped all the columns where null values are found

Empty DataFrame
Columns: []
Index: [0, 1, 2, 3]

Fill Missing Values

Instead of deleting data, you can fill it:

Fill with a constant:
df.fillna(0)
Fill with mean (for numeric columns):
df["Age"].fillna(df["Age"].mean())

In [68]:
df

   Name   Age    City
0  Amit  25.0   Delhi
1  Riya   NaN  Mumbai
2   Raj  30.0    None
3  None  22.0  Jaipur

In [74]:
#This is for non numeric columns
df['City'] = df['City'].fillna("unknown") # we have filled city column with unknown to all the none

In [75]:
df

   Name   Age     City
0  Amit  25.0    Delhi
1  Riya   NaN   Mumbai
2   Raj  30.0  unknown
3  None  22.0   Jaipur

In [78]:
#this is for numeric columns
df['Age'] = df['Age'].fillna(df['Age'].mean())

In [79]:
df

   Name        Age     City
0  Amit  25.000000    Delhi
1  Riya  25.666667   Mumbai
2   Raj  30.000000  unknown
3  None  22.000000   Jaipur

In [80]:
df['Name'] = df['Name'].fillna('unknown')

In [81]:
df

      Name        Age     City
0     Amit  25.000000    Delhi
1     Riya  25.666667   Mumbai
2      Raj  30.000000  unknown
3  unknown  22.000000   Jaipur

# Data Cleaning & Transformation

Example Dataset
import pandas as pd

data = {
    "Name": ["Amit ", " riya", "RAJ", "Ankit"],
    "Age": ["25", "30", "22", "twenty"],
    "City": ["Delhi", "mumbai", "DELHI", "Jaipur"]
}

df = pd.DataFrame(data)
print(df)

👉 Problems here:

Extra spaces
Inconsistent casing
Wrong data types
Invalid values ("twenty")

In [130]:
data = {
    "Name": ["Amit ", " riya", "RAJ", "Ankit"],
    "Age": ["25", "30", "22", "twenty"],
    "City": ["Delhi", "mumbai", "DELHI", "Jaipur"]
}

df = pd.DataFrame(data)
print(df)

    Name     Age    City
0  Amit       25   Delhi
1   riya      30  mumbai
2    RAJ      22   DELHI
3  Ankit  twenty  Jaipur

In [86]:
#we will clean and make this data consistent one by one

df['Name'] = df['Name'].str.strip() #str.strip has removed extra spaces

In [87]:
df

    Name     Age    City
0   Amit      25   Delhi
1   riya      30  mumbai
2    RAJ      22   DELHI
3  Ankit  twenty  Jaipur

In [88]:
#now we will make Name column consistent after stripping we have 3 options
#str.lower() lower case 
#str.capitalize() first letter capital
#str.title() every words first letter capital 


df['Name'] = df['Name'].str.capitalize()

In [89]:
df

    Name     Age    City
0   Amit      25   Delhi
1   Riya      30  mumbai
2    Raj      22   DELHI
3  Ankit  twenty  Jaipur

### Now we will go to second column  Age and fix its datatype | errors="coerce" will raise exception and convert to NAN

In [92]:
df['Age'] = pd.to_numeric(df['Age'],errors="coerce") #,errors="coerce" is used with to_numeric and to_datetime and change it to NAn

In [93]:
df

    Name   Age    City
0   Amit  25.0   Delhi
1   Riya  30.0  mumbai
2    Raj  22.0   DELHI
3  Ankit   NaN  Jaipur

In [94]:
df['Age'] = df['Age'].fillna(df['Age'].mean())

In [95]:
df

    Name        Age    City
0   Amit  25.000000   Delhi
1   Riya  30.000000  mumbai
2    Raj  22.000000   DELHI
3  Ankit  25.666667  Jaipur

In [ ]:
# we have fixed Name and Age column now we will filx City column

In [97]:
df['City'] = df['City'].str.capitalize()

In [98]:
df

    Name        Age    City
0   Amit  25.000000   Delhi
1   Riya  30.000000  Mumbai
2    Raj  22.000000   Delhi
3  Ankit  25.666667  Jaipur

Renaming columns (rename)
Changing data types (astype)

df['column_name'] = df['column_name'].astype(int)

In [131]:
df

    Name     Age    City
0  Amit       25   Delhi
1   riya      30  mumbai
2    RAJ      22   DELHI
3  Ankit  twenty  Jaipur

In [132]:
df.rename(columns = {
    'Name' : 'Nam'
})

     Nam     Age    City
0  Amit       25   Delhi
1   riya      30  mumbai
2    RAJ      22   DELHI
3  Ankit  twenty  Jaipur

## IMP we can use .apply(function) to fill something 

Example :- 

def age_group(x):
    if x < 25:
        return "Young"
    else:
        return "Adult"

df["Category"] = df["Age"].apply(age_group)

### Now we will test date missing columns 

if we want to fix datedatype we need to convert it to a NaN using .to_datetime,errors="coerce" 
and then either forward fill = ffill which will fill previous date and backward fill = bffill which will fill next row date

In [99]:

data = {
    "Date": ["2024-01-01", None, "2024-01-03", None]
}

df = pd.DataFrame(data)

In [100]:
df

         Date
0  2024-01-01
1        None
2  2024-01-03
3        None

In [102]:
df['Date'] = pd.to_datetime(df['Date'],errors = 'coerce')

In [103]:
df

        Date
0 2024-01-01
1        NaT
2 2024-01-03
3        NaT

In [106]:
df['Date'] = df['Date'].fillna(method= 'bfill')

In [105]:
df

        Date
0 2024-01-01
1 2024-01-01
2 2024-01-03
3 2024-01-03

Merging & Joining DataFrames

👉 Used when you have multiple tables (datasets) and want to combine them.

Think like Excel VLOOKUP or SQL JOIN.

Joining datasets using pd.merge(on = " " , how = " " )

for joininin we have

1) Merge - Merge two datasets in inner join , left join , right join , outer join like in SQL 

2) Contact - stacking two datasets obove one another

In [108]:
df1 = pd.DataFrame({
    "CustomerID": [1, 2, 3],
    "Name": ["Amit", "Riya", "Raj"]
})



df2 = pd.DataFrame({
    "CustomerID": [1, 2, 4],
    "OrderAmount": [500, 700, 300]
})

In [ ]:
#we will first use Merge if we want to merge another dataset in main then we use df1.merge(df2...) 
# we can also use pd.merge(df1,df2)

#lets check both

In [109]:
df1.merge(df2,on = 'CustomerID') # merged like inner join

   CustomerID  Name  OrderAmount
0           1  Amit          500
1           2  Riya          700

In [110]:
#lets try second syntax

pd.merge(df1,df2) #automatically chose column column and did inner join

   CustomerID  Name  OrderAmount
0           1  Amit          500
1           2  Riya          700

In [112]:
pd.merge(df1,df2, how = 'left') #left join mean all the columns from df1 and only matching from df2

   CustomerID  Name  OrderAmount
0           1  Amit        500.0
1           2  Riya        700.0
2           3   Raj          NaN

In [113]:
pd.merge(df1,df2,how = 'right') #right join mean all the columns from df1 and only matching from df2

   CustomerID  Name  OrderAmount
0           1  Amit          500
1           2  Riya          700
2           4   NaN          300

In [115]:
pd.merge(df1,df2 , how = 'outer') #outer join keep all the rows non matching values will NaN

   CustomerID  Name  OrderAmount
0           1  Amit        500.0
1           2  Riya        700.0
2           3   Raj          NaN
3           4   NaN        300.0

Merge on Different Column Names

when column names are different either we can rename the columns and join 
or we can do pd.merge(df1,df1,left_on = ' ' , right_on = ' ' )

In [124]:
df3 = pd.DataFrame({
    "CustomerID": [1, 2, 3],
    "Name": ["Amit", "Riya", "Raj"]
})



df4 = pd.DataFrame({
    "CustID": [1, 2, 4],
    "OrderAmount": [500, 700, 300]
})

In [121]:
pd.merge(df3,df4,left_on = 'CustomerID',right_on = 'CustID') #inner join based on different column names we can use how = '' for left right

   CustomerID  Name  CustID  OrderAmount
0           1  Amit       1          500
1           2  Riya       2          700

In [122]:
pd.merge(df3,df4,left_on = 'CustomerID',right_on = 'CustID',how = 'left') #inner join based on different column names, using how

   CustomerID  Name  CustID  OrderAmount
0           1  Amit     1.0        500.0
1           2  Riya     2.0        700.0
2           3   Raj     NaN          NaN

In [127]:
# 2 ) concat

# 1. The "List" Rule
# 2 The Axis Rule (Direction) axis = 0 , which is defailt and 


pd.concat([df1,df2]) #we need to pass dataframes into lists

   CustomerID  Name  OrderAmount
0           1  Amit          NaN
1           2  Riya          NaN
2           3   Raj          NaN
0           1   NaN        500.0
1           2   NaN        700.0
2           4   NaN        300.0

In [128]:
pd.concat([df3,df4]) #column names are different  hence side by side

   CustomerID  Name  CustID  OrderAmount
0         1.0  Amit     NaN          NaN
1         2.0  Riya     NaN          NaN
2         3.0   Raj     NaN          NaN
0         NaN   NaN     1.0        500.0
1         NaN   NaN     2.0        700.0
2         NaN   NaN     4.0        300.0