<h2 align="center" style="color:blue">Codebasics Python Course: Exercise - Functions, Dict, Tuples, File Handling</h2>

Imagine you run a loyalty program where customers earn rewards based on the total amount they have spent. The rewards levels are defined based on the total purchase amount. Based on this scenario, complete the following tasks

### Task 1

You are given a file called ```customers.txt``` that contains the name of the customer and total amount they spent. Read this file line by line and save the customer name and total amount in a dictionary.

For example, customers.txt file will content the data in the following format,
```
Srinivas,120
John,250
Maria,150
Smith,510
Anjali,45
```

You will read this and build a dictionary like this,
```
{
    "Srinivas": 120,
    "John": 250,
    "Maria": 150,
    "Smith": 510,
    "Anjali": 45
}
```

In [1]:
# write your code here

### Task 2

The rewards levels are defined below based on the total purchase amount. Using this define a function called calculate_rewards that takes total as input and returns the reward.

```
1. Bronze: Total purchases $100-$199
1. Silver: Total purchases $200-$499
1. Gold: Total purchases $500+
```

In [44]:
# write your code here
import pandas as pd

file = pd.read_csv("customers.txt",sep = ',',header=None)
file[1]

0    120
1    250
2    150
3    510
4     45
5    100
6     99
Name: 1, dtype: int64

In [24]:
file = file.rename(columns ={ 0:'name', 1:'purchase'})
file

       name  purchase
0  Srinivas       120
1      John       250
2     Maria       150
3     Smith       510
4    Anjali        45
5     Navin       100
6   Santosh        99

In [25]:
import numpy as np

In [26]:
file['tier'] = np.select(
    
    [file['purchase'].between(100,199),
    file['purchase'].between(200,499),
    file['purchase']>500],
[
    'Bronze',
    'Silver',
    'Gold'
],
    default = 'No Tier'
    
)

In [27]:
file

       name  purchase     tier
0  Srinivas       120   Bronze
1      John       250   Silver
2     Maria       150   Bronze
3     Smith       510     Gold
4    Anjali        45  No Tier
5     Navin       100   Bronze
6   Santosh        99  No Tier

### Task 3

Now for each of the customers in our customers_dict, calculate the rewards and build a customers_summary dictionary that looks like the following, (key is the name of the customer and the value is a tuple containing total amount and rewards level)

```
{
    'Srinivas': (120, 'Bronze'),
    'John': (250, 'Silver'),
    'Maria': (150, 'Bronze'),
    'Smith': (510, 'Gold'),
    'Anjali': (45, 'None')
}
```

In [3]:
# write your code here
done above

### Task 4

Now stitch all of the above code together and create a function that takes file name as input and returns the customer_summary dictionary.

```
def process_customer_data(file_name):
    # return customer_summary dict
```

In [49]:
# write your code here
import pandas as pd
import numpy as np
def process_customer_data(file_name,amount_col,sep=','):
    df = pd.read_csv(file_name,sep=sep,header = None)
    df = df.rename(columns ={ 0:'name', 1:'purchase'})
    conditions = [
        df[amount_col].between(100,199),
        df[amount_col].between(200,499),
        df[amount_col]>500
    ]
    
    choice = [
        'Bronze',
        'Silver',
        'Gold'
    ]
 
    
    df['teir'] = np.select(conditions,choice,default = 'None')
    return df

In [50]:
process_customer_data('customers.txt','purchase')

       name  purchase    teir
0  Srinivas       120  Bronze
1      John       250  Silver
2     Maria       150  Bronze
3     Smith       510    Gold
4    Anjali        45    None
5     Navin       100  Bronze
6   Santosh        99    None